### PR TITLE
Update Find Second Largest.cpp

### PR DESCRIPTION
**Pull request by Kushagra2007**
I have replaced the way with another one. As it is faster than an array. In this method, I've summed up the total integers and subtracting them from the maximum and minimum input. And we'll get the second largest.

### CODE REVIEW

**Comment by JayantGoel001** [comment]
> I have replaced the way with another one. As it is faster than an array. In this method, I've summed up the total integers and subtracting them from the maximum and minimum input. And we'll get the second largest.

It is a good approach 
Do one thing instead of deleting my file 
Create a new file with the same name + "2".

LGTM👍

**Review by JayantGoel001 — APPROVED** [review]

**Comment by Kushagra2007** [comment]
I have created a new file named "Find Second Largest 2". I'll be looking for the repo for any further changes and will inform you if any.

**Review by Kushagra2007 — COMMENTED** [review]
I have created a new file named "Find Second Largest 2". I'll be looking at the repo for any further changes and will inform you if any.

**Review by JayantGoel001 — APPROVED** [review]

**Comment by JayantGoel001** [comment]
@all-contributors please add @Kushagra2007  for code

**Comment by JayantGoel001** [comment]
@all-contributors please add @JayantGoel001 for code, ideas, test, maintenance, doc

**Comment by JayantGoel001** [comment]
@all-contributors please add @JayantGoel001 for code, ideas, test, maintenance, doc

**Pull request merged**
